package org.praxisplatform.config.ai.authoring;

import com.fasterxml.jackson.databind.JsonNode;
import java.util.List;

public record AgenticAuthoringIntentResolutionResult(
        boolean valid,
        String operationKind,
        String artifactKind,
        String changeKind,
        String authoringProfile,
        String targetApp,
        String targetComponentId,
        AgenticAuthoringTarget target,
        AgenticAuthoringCandidate selectedCandidate,
        List<AgenticAuthoringCandidate> candidates,
        AgenticAuthoringGateResult gate,
        String effectivePrompt,
        String assistantMessage,
        JsonNode apiCatalogAnswer,
        List<AgenticAuthoringQuickReply> quickReplies,
        AgenticAuthoringPendingClarification pendingClarification,
        List<String> clarificationQuestions,
        List<String> warnings,
        List<String> failureCodes,
        JsonNode currentPageSummary,
        JsonNode llmDiagnostics
) {
    public AgenticAuthoringIntentResolutionResult(
            boolean valid,
            String operationKind,
            String artifactKind,
            String changeKind,
            String authoringProfile,
            String targetApp,
            String targetComponentId,
            AgenticAuthoringTarget target,
            AgenticAuthoringCandidate selectedCandidate,
            List<AgenticAuthoringCandidate> candidates,
            AgenticAuthoringGateResult gate,
            String effectivePrompt,
            String assistantMessage,
            List<AgenticAuthoringQuickReply> quickReplies,
            List<String> clarificationQuestions,
            List<String> warnings,
            List<String> failureCodes,
            JsonNode currentPageSummary) {
        this(
                valid,
                operationKind,
                artifactKind,
                changeKind,
                authoringProfile,
                targetApp,
                targetComponentId,
                target,
                selectedCandidate,
                candidates,
                gate,
                effectivePrompt,
                assistantMessage,
                null,
                quickReplies,
                null,
                clarificationQuestions,
                warnings,
                failureCodes,
                currentPageSummary,
                null);
    }

    public AgenticAuthoringIntentResolutionResult(
            boolean valid,
            String operationKind,
            String artifactKind,
            String changeKind,
            String authoringProfile,
            String targetApp,
            String targetComponentId,
            AgenticAuthoringTarget target,
            AgenticAuthoringCandidate selectedCandidate,
            List<AgenticAuthoringCandidate> candidates,
            AgenticAuthoringGateResult gate,
            String effectivePrompt,
            String assistantMessage,
            JsonNode apiCatalogAnswer,
            List<AgenticAuthoringQuickReply> quickReplies,
            List<String> clarificationQuestions,
            List<String> warnings,
            List<String> failureCodes,
            JsonNode currentPageSummary) {
        this(
                valid,
                operationKind,
                artifactKind,
                changeKind,
                authoringProfile,
                targetApp,
                targetComponentId,
                target,
                selectedCandidate,
                candidates,
                gate,
                effectivePrompt,
                assistantMessage,
                apiCatalogAnswer,
                quickReplies,
                null,
                clarificationQuestions,
                warnings,
                failureCodes,
                currentPageSummary,
                null);
    }

    public AgenticAuthoringIntentResolutionResult(
            boolean valid,
            String operationKind,
            String artifactKind,
            String changeKind,
            String authoringProfile,
            String targetApp,
            String targetComponentId,
            AgenticAuthoringTarget target,
            AgenticAuthoringCandidate selectedCandidate,
            List<AgenticAuthoringCandidate> candidates,
            AgenticAuthoringGateResult gate,
            String effectivePrompt,
            String assistantMessage,
            JsonNode apiCatalogAnswer,
            List<AgenticAuthoringQuickReply> quickReplies,
            AgenticAuthoringPendingClarification pendingClarification,
            List<String> clarificationQuestions,
            List<String> warnings,
            List<String> failureCodes,
            JsonNode currentPageSummary) {
        this(
                valid,
                operationKind,
                artifactKind,
                changeKind,
                authoringProfile,
                targetApp,
                targetComponentId,
                target,
                selectedCandidate,
                candidates,
                gate,
                effectivePrompt,
                assistantMessage,
                apiCatalogAnswer,
                quickReplies,
                pendingClarification,
                clarificationQuestions,
                warnings,
                failureCodes,
                currentPageSummary,
                null);
    }

    public AgenticAuthoringIntentResolutionResult(
            boolean valid,
            String operationKind,
            String artifactKind,
            String changeKind,
            String authoringProfile,
            String targetApp,
            String targetComponentId,
            AgenticAuthoringTarget target,
            AgenticAuthoringCandidate selectedCandidate,
            List<AgenticAuthoringCandidate> candidates,
            AgenticAuthoringGateResult gate,
            List<String> clarificationQuestions,
            List<String> warnings,
            List<String> failureCodes,
            JsonNode currentPageSummary) {
        this(
                valid,
                operationKind,
                artifactKind,
                changeKind,
                authoringProfile,
                targetApp,
                targetComponentId,
                target,
                selectedCandidate,
                candidates,
                gate,
                null,
                null,
                null,
                List.of(),
                null,
                clarificationQuestions,
                warnings,
                failureCodes,
                currentPageSummary,
                null);
    }
}
