package org.praxisplatform.config.ai.authoring;

import com.fasterxml.jackson.databind.JsonNode;
import java.util.List;

public record AgenticAuthoringIntentResolutionResult(
        boolean valid,
        String operationKind,
        String artifactKind,
        String changeKind,
        String authoringProfile,
        String targetApp,
        String targetComponentId,
        AgenticAuthoringTarget target,
        AgenticAuthoringCandidate selectedCandidate,
        List<AgenticAuthoringCandidate> candidates,
        AgenticAuthoringGateResult gate,
        String effectivePrompt,
        String assistantMessage,
        JsonNode assistantContent,
        JsonNode apiCatalogAnswer,
        List<AgenticAuthoringQuickReply> quickReplies,
        AgenticAuthoringPendingClarification pendingClarification,
        List<String> clarificationQuestions,
        List<String> warnings,
        List<String> failureCodes,
        JsonNode currentPageSummary,
        JsonNode llmDiagnostics,
        AgenticAuthoringVisualizationDecision visualizationDecision,
        AgenticAuthoringSemanticDecision semanticDecision
) {
    public AgenticAuthoringIntentResolutionResult {
        if (semanticDecision == null) {
            semanticDecision = AgenticAuthoringSemanticDecision.from(
                    operationKind,
                    artifactKind,
                    changeKind,
                    selectedCandidate,
                    candidates,
                    visualizationDecision,
                    warnings,
                    llmDiagnostics);
        }
    }

    public AgenticAuthoringIntentResolutionResult(
            boolean valid,
            String operationKind,
            String artifactKind,
            String changeKind,
            String authoringProfile,
            String targetApp,
            String targetComponentId,
            AgenticAuthoringTarget target,
            AgenticAuthoringCandidate selectedCandidate,
            List<AgenticAuthoringCandidate> candidates,
            AgenticAuthoringGateResult gate,
            String effectivePrompt,
            String assistantMessage,
            JsonNode apiCatalogAnswer,
            List<AgenticAuthoringQuickReply> quickReplies,
            AgenticAuthoringPendingClarification pendingClarification,
            List<String> clarificationQuestions,
            List<String> warnings,
            List<String> failureCodes,
            JsonNode currentPageSummary,
            JsonNode llmDiagnostics,
            AgenticAuthoringVisualizationDecision visualizationDecision,
            AgenticAuthoringSemanticDecision semanticDecision) {
        this(
                valid,
                operationKind,
                artifactKind,
                changeKind,
                authoringProfile,
                targetApp,
                targetComponentId,
                target,
                selectedCandidate,
                candidates,
                gate,
                effectivePrompt,
                assistantMessage,
                null,
                apiCatalogAnswer,
                quickReplies,
                pendingClarification,
                clarificationQuestions,
                warnings,
                failureCodes,
                currentPageSummary,
                llmDiagnostics,
                visualizationDecision,
                semanticDecision);
    }

    public AgenticAuthoringIntentResolutionResult(
            boolean valid,
            String operationKind,
            String artifactKind,
            String changeKind,
            String authoringProfile,
            String targetApp,
            String targetComponentId,
            AgenticAuthoringTarget target,
            AgenticAuthoringCandidate selectedCandidate,
            List<AgenticAuthoringCandidate> candidates,
            AgenticAuthoringGateResult gate,
            String effectivePrompt,
            String assistantMessage,
            JsonNode apiCatalogAnswer,
            List<AgenticAuthoringQuickReply> quickReplies,
            AgenticAuthoringPendingClarification pendingClarification,
            List<String> clarificationQuestions,
            List<String> warnings,
            List<String> failureCodes,
            JsonNode currentPageSummary,
            JsonNode llmDiagnostics,
            AgenticAuthoringVisualizationDecision visualizationDecision) {
        this(
                valid,
                operationKind,
                artifactKind,
                changeKind,
                authoringProfile,
                targetApp,
                targetComponentId,
                target,
                selectedCandidate,
                candidates,
                gate,
                effectivePrompt,
                assistantMessage,
                null,
                apiCatalogAnswer,
                quickReplies,
                pendingClarification,
                clarificationQuestions,
                warnings,
                failureCodes,
                currentPageSummary,
                llmDiagnostics,
                visualizationDecision,
                null);
    }

    public AgenticAuthoringIntentResolutionResult(
            boolean valid,
            String operationKind,
            String artifactKind,
            String changeKind,
            String authoringProfile,
            String targetApp,
            String targetComponentId,
            AgenticAuthoringTarget target,
            AgenticAuthoringCandidate selectedCandidate,
            List<AgenticAuthoringCandidate> candidates,
            AgenticAuthoringGateResult gate,
            String effectivePrompt,
            String assistantMessage,
            JsonNode apiCatalogAnswer,
            List<AgenticAuthoringQuickReply> quickReplies,
            AgenticAuthoringPendingClarification pendingClarification,
            List<String> clarificationQuestions,
            List<String> warnings,
            List<String> failureCodes,
            JsonNode currentPageSummary,
            JsonNode llmDiagnostics) {
        this(
                valid,
                operationKind,
                artifactKind,
                changeKind,
                authoringProfile,
                targetApp,
                targetComponentId,
                target,
                selectedCandidate,
                candidates,
                gate,
                effectivePrompt,
                assistantMessage,
                null,
                apiCatalogAnswer,
                quickReplies,
                pendingClarification,
                clarificationQuestions,
                warnings,
                failureCodes,
                currentPageSummary,
                llmDiagnostics,
                null,
                null);
    }

    public AgenticAuthoringIntentResolutionResult(
            boolean valid,
            String operationKind,
            String artifactKind,
            String changeKind,
            String authoringProfile,
            String targetApp,
            String targetComponentId,
            AgenticAuthoringTarget target,
            AgenticAuthoringCandidate selectedCandidate,
            List<AgenticAuthoringCandidate> candidates,
            AgenticAuthoringGateResult gate,
            String effectivePrompt,
            String assistantMessage,
            List<AgenticAuthoringQuickReply> quickReplies,
            List<String> clarificationQuestions,
            List<String> warnings,
            List<String> failureCodes,
            JsonNode currentPageSummary) {
        this(
                valid,
                operationKind,
                artifactKind,
                changeKind,
                authoringProfile,
                targetApp,
                targetComponentId,
                target,
                selectedCandidate,
                candidates,
                gate,
                effectivePrompt,
                assistantMessage,
                null,
                null,
                quickReplies,
                null,
                clarificationQuestions,
                warnings,
                failureCodes,
                currentPageSummary,
                null,
                null,
                null);
    }

    public AgenticAuthoringIntentResolutionResult(
            boolean valid,
            String operationKind,
            String artifactKind,
            String changeKind,
            String authoringProfile,
            String targetApp,
            String targetComponentId,
            AgenticAuthoringTarget target,
            AgenticAuthoringCandidate selectedCandidate,
            List<AgenticAuthoringCandidate> candidates,
            AgenticAuthoringGateResult gate,
            String effectivePrompt,
            String assistantMessage,
            JsonNode apiCatalogAnswer,
            List<AgenticAuthoringQuickReply> quickReplies,
            List<String> clarificationQuestions,
            List<String> warnings,
            List<String> failureCodes,
            JsonNode currentPageSummary) {
        this(
                valid,
                operationKind,
                artifactKind,
                changeKind,
                authoringProfile,
                targetApp,
                targetComponentId,
                target,
                selectedCandidate,
                candidates,
                gate,
                effectivePrompt,
                assistantMessage,
                null,
                apiCatalogAnswer,
                quickReplies,
                null,
                clarificationQuestions,
                warnings,
                failureCodes,
                currentPageSummary,
                null,
                null,
                null);
    }

    public AgenticAuthoringIntentResolutionResult(
            boolean valid,
            String operationKind,
            String artifactKind,
            String changeKind,
            String authoringProfile,
            String targetApp,
            String targetComponentId,
            AgenticAuthoringTarget target,
            AgenticAuthoringCandidate selectedCandidate,
            List<AgenticAuthoringCandidate> candidates,
            AgenticAuthoringGateResult gate,
            String effectivePrompt,
            String assistantMessage,
            JsonNode apiCatalogAnswer,
            List<AgenticAuthoringQuickReply> quickReplies,
            AgenticAuthoringPendingClarification pendingClarification,
            List<String> clarificationQuestions,
            List<String> warnings,
            List<String> failureCodes,
            JsonNode currentPageSummary) {
        this(
                valid,
                operationKind,
                artifactKind,
                changeKind,
                authoringProfile,
                targetApp,
                targetComponentId,
                target,
                selectedCandidate,
                candidates,
                gate,
                effectivePrompt,
                assistantMessage,
                null,
                apiCatalogAnswer,
                quickReplies,
                pendingClarification,
                clarificationQuestions,
                warnings,
                failureCodes,
                currentPageSummary,
                null,
                null,
                null);
    }

    public AgenticAuthoringIntentResolutionResult(
            boolean valid,
            String operationKind,
            String artifactKind,
            String changeKind,
            String authoringProfile,
            String targetApp,
            String targetComponentId,
            AgenticAuthoringTarget target,
            AgenticAuthoringCandidate selectedCandidate,
            List<AgenticAuthoringCandidate> candidates,
            AgenticAuthoringGateResult gate,
            List<String> clarificationQuestions,
            List<String> warnings,
            List<String> failureCodes,
            JsonNode currentPageSummary) {
        this(
                valid,
                operationKind,
                artifactKind,
                changeKind,
                authoringProfile,
                targetApp,
                targetComponentId,
                target,
                selectedCandidate,
                candidates,
                gate,
                null,
                null,
                null,
                null,
                List.of(),
                null,
                clarificationQuestions,
                warnings,
                failureCodes,
                currentPageSummary,
                null,
                null,
                null);
    }

    public AgenticAuthoringIntentResolutionResult withAssistantContent(JsonNode assistantContent) {
        return new AgenticAuthoringIntentResolutionResult(
                valid,
                operationKind,
                artifactKind,
                changeKind,
                authoringProfile,
                targetApp,
                targetComponentId,
                target,
                selectedCandidate,
                candidates,
                gate,
                effectivePrompt,
                assistantMessage,
                assistantContent,
                apiCatalogAnswer,
                quickReplies,
                pendingClarification,
                clarificationQuestions,
                warnings,
                failureCodes,
                currentPageSummary,
                llmDiagnostics,
                visualizationDecision,
                semanticDecision);
    }
}
