package org.praxisplatform.config.ai.authoring;

import com.fasterxml.jackson.databind.JsonNode;
import java.util.List;

public record AgenticAuthoringTurnStreamRequest(
        String userPrompt,
        String targetApp,
        String targetComponentId,
        String currentRoute,
        JsonNode currentPage,
        String selectedWidgetKey,
        String provider,
        String model,
        String apiKey,
        String sessionId,
        String clientTurnId,
        List<AgenticAuthoringConversationMessage> conversationMessages,
        AgenticAuthoringPendingClarification pendingClarification,
        List<AgenticAuthoringAttachmentSummary> attachmentSummaries,
        JsonNode contextHints,
        AgenticAuthoringComponentCapabilitiesResult componentCapabilities,
        AgenticAuthoringSemanticDecision activeSemanticDecision,
        JsonNode diagnostics,
        List<JsonNode> runtimeComponentObservations,
        String runtimeComponentObservationTrustBoundary
) {
    public AgenticAuthoringTurnStreamRequest(
            String userPrompt,
            String targetApp,
            String targetComponentId,
            String currentRoute,
            JsonNode currentPage,
            String selectedWidgetKey,
            String provider,
            String model,
            String apiKey,
            String sessionId,
            String clientTurnId,
            List<AgenticAuthoringConversationMessage> conversationMessages,
            AgenticAuthoringPendingClarification pendingClarification,
            List<AgenticAuthoringAttachmentSummary> attachmentSummaries,
            JsonNode contextHints,
            AgenticAuthoringComponentCapabilitiesResult componentCapabilities,
            AgenticAuthoringSemanticDecision activeSemanticDecision) {
        this(
                userPrompt,
                targetApp,
                targetComponentId,
                currentRoute,
                currentPage,
                selectedWidgetKey,
                provider,
                model,
                apiKey,
                sessionId,
                clientTurnId,
                conversationMessages,
                pendingClarification,
                attachmentSummaries,
                contextHints,
                componentCapabilities,
                activeSemanticDecision,
                null,
                null,
                null);
    }

    public AgenticAuthoringTurnStreamRequest(
            String userPrompt,
            String targetApp,
            String targetComponentId,
            String currentRoute,
            JsonNode currentPage,
            String selectedWidgetKey,
            String provider,
            String model,
            String apiKey,
            String sessionId,
            String clientTurnId,
            List<AgenticAuthoringConversationMessage> conversationMessages,
            AgenticAuthoringPendingClarification pendingClarification,
            List<AgenticAuthoringAttachmentSummary> attachmentSummaries,
            JsonNode contextHints,
            AgenticAuthoringComponentCapabilitiesResult componentCapabilities,
            AgenticAuthoringSemanticDecision activeSemanticDecision,
            List<JsonNode> runtimeComponentObservations,
            String runtimeComponentObservationTrustBoundary) {
        this(
                userPrompt,
                targetApp,
                targetComponentId,
                currentRoute,
                currentPage,
                selectedWidgetKey,
                provider,
                model,
                apiKey,
                sessionId,
                clientTurnId,
                conversationMessages,
                pendingClarification,
                attachmentSummaries,
                contextHints,
                componentCapabilities,
                activeSemanticDecision,
                null,
                runtimeComponentObservations,
                runtimeComponentObservationTrustBoundary);
    }

    public AgenticAuthoringTurnStreamRequest(
            String userPrompt,
            String targetApp,
            String targetComponentId,
            String currentRoute,
            JsonNode currentPage,
            String selectedWidgetKey,
            String provider,
            String model,
            String apiKey,
            String sessionId,
            String clientTurnId,
            List<AgenticAuthoringConversationMessage> conversationMessages,
            AgenticAuthoringPendingClarification pendingClarification,
            List<AgenticAuthoringAttachmentSummary> attachmentSummaries,
            JsonNode contextHints,
            AgenticAuthoringComponentCapabilitiesResult componentCapabilities) {
        this(
                userPrompt,
                targetApp,
                targetComponentId,
                currentRoute,
                currentPage,
                selectedWidgetKey,
                provider,
                model,
                apiKey,
                sessionId,
                clientTurnId,
                conversationMessages,
                pendingClarification,
                attachmentSummaries,
                contextHints,
                componentCapabilities,
                null,
                null,
                null,
                null);
    }
}
