CREATE TYPE IF NOT EXISTS jsonb AS TEXT;
CREATE TYPE IF NOT EXISTS vector AS VARCHAR;

CREATE TABLE ai_registry (
  id UUID PRIMARY KEY,
  registry_type VARCHAR(64) NOT NULL,
  registry_key VARCHAR(255) NOT NULL,
  component_type VARCHAR(64),
  scope VARCHAR(32) NOT NULL,
  scope_key VARCHAR(255) NOT NULL,
  payload jsonb NOT NULL,
  version BIGINT NOT NULL,
  etag UUID NOT NULL,
  tags jsonb,
  source VARCHAR(64),
  source_ref VARCHAR(255),
  status VARCHAR(32) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  created_by VARCHAR(255),
  updated_by VARCHAR(255),
  embedding vector
);

CREATE TABLE api_metadata (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  path VARCHAR(1024) NOT NULL,
  method VARCHAR(16) NOT NULL,
  tenant_id VARCHAR(255) NOT NULL,
  environment VARCHAR(255) NOT NULL,
  service_key VARCHAR(255) NOT NULL,
  release_id VARCHAR(255) NOT NULL,
  release_version VARCHAR(255),
  generated_at VARCHAR(255),
  tags VARCHAR(1024),
  summary VARCHAR(1024),
  description VARCHAR(4096),
  operation_id VARCHAR(255),
  request_schema TEXT,
  response_schema TEXT,
  parameters TEXT,
  raw_json TEXT,
  embedding vector
);

CREATE TABLE domain_catalog_release (
  id UUID PRIMARY KEY,
  release_key VARCHAR(255) NOT NULL,
  schema_version VARCHAR(64) NOT NULL,
  service_key VARCHAR(255),
  service_name VARCHAR(255),
  service_version VARCHAR(64),
  resource_key VARCHAR(255),
  generated_at TIMESTAMP WITH TIME ZONE,
  source_hash VARCHAR(128),
  tenant_id VARCHAR(128),
  environment VARCHAR(128),
  raw_payload jsonb NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE UNIQUE INDEX uk_domain_catalog_release_scope_key
  ON domain_catalog_release (tenant_id, environment, release_key);

CREATE TABLE domain_catalog_item (
  id UUID PRIMARY KEY,
  release_id UUID NOT NULL REFERENCES domain_catalog_release(id) ON DELETE CASCADE,
  item_type VARCHAR(32) NOT NULL,
  item_key VARCHAR(512) NOT NULL,
  context_key VARCHAR(255),
  node_type VARCHAR(64),
  binding_type VARCHAR(64),
  edge_type VARCHAR(64),
  payload jsonb NOT NULL,
  searchable_text TEXT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT uk_domain_catalog_item UNIQUE (release_id, item_type, item_key)
);
