CREATE TYPE IF NOT EXISTS vector AS TEXT;
CREATE TYPE IF NOT EXISTS jsonb AS TEXT;

CREATE TABLE config_entries (
  id UUID PRIMARY KEY,
  config_key VARCHAR(255) NOT NULL UNIQUE,
  config_value VARCHAR(1024) NOT NULL
);

CREATE TABLE ai_registry (
  id UUID PRIMARY KEY,
  registry_type VARCHAR(64) NOT NULL,
  registry_key VARCHAR(255) NOT NULL,
  component_type VARCHAR(64),
  scope VARCHAR(32) NOT NULL,
  scope_key VARCHAR(255) NOT NULL,
  payload jsonb NOT NULL,
  version BIGINT NOT NULL,
  etag UUID NOT NULL,
  tags jsonb,
  source VARCHAR(64),
  source_ref VARCHAR(255),
  status VARCHAR(32) NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  created_by VARCHAR(255),
  updated_by VARCHAR(255),
  embedding vector
);

CREATE TABLE api_metadata (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  description VARCHAR(255),
  embedding vector,
  method VARCHAR(255) NOT NULL,
  operation_id VARCHAR(255),
  parameters TEXT,
  path VARCHAR(255) NOT NULL,
  raw_json TEXT,
  request_schema TEXT,
  response_schema TEXT,
  summary VARCHAR(255),
  tags VARCHAR(255),
  UNIQUE (path, method)
);

CREATE TABLE ui_user_config (
  id UUID PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
  version BIGINT NOT NULL,
  etag UUID NOT NULL,
  component_type VARCHAR(64) NOT NULL,
  environment VARCHAR(64),
  component_id VARCHAR(255) NOT NULL,
  payload jsonb NOT NULL,
  tags jsonb,
  tenant_id VARCHAR(255) NOT NULL,
  updated_by VARCHAR(255),
  user_id VARCHAR(255),
  UNIQUE (tenant_id, user_id, component_type, component_id, environment)
);